When we call assertRaises, we should pass the function name and function argumentes as individual attributes. Before, I was calling the function which was evaluating and was throwing an exception. 

The latest file rectified this error. Please compare with the old version.
